/**
 * Types shared between the Electron main process (file storage, AI stub) and the
 * renderer. Keep this module dependency-free so both sides can import it.
 */

/* ------------------------------------------------------------------ catalog */

export type Baseline = 'Low' | 'Moderate' | 'High';
export type BaselineFilter = Baseline | 'All';
export type FrameworkMode = 'nist' | 'va';

export type ControlStatus = 'active' | 'withdrawn' | 'not_selected';
export type ControlType = 'technical' | 'administrative' | 'physical';
export type ControlDesignation = 'common' | 'hybrid' | 'system_specific' | 'inherited';

export interface CatalogParameter {
  parameter_id: string;
  description: string;
}

export interface CatalogNist {
  baselines: Baseline[];
  control_statement: string;
  discussion?: string;
  related_controls?: string[];
  assessment_objectives?: string[];
  parameters?: CatalogParameter[];
  /** Verbatim from csf.tools, merged in at load time from catalog/csf-guidance.json. */
  control_statement_verbatim?: string;
  supplemental_guidance?: string;
}

export interface VaOdpValue {
  parameter: string;
  value: string;
}

export interface VaBaselineAllocation {
  low?: string;
  moderate?: string;
  high?: string;
}

export interface VaOverlay {
  applies: boolean;
  priority_code?: string;
  control_designation?: ControlDesignation;
  va_baseline_allocation?: VaBaselineAllocation;
  va_odp_values?: VaOdpValue[];
  va_implementation_guidance?: string;
  va_specific_requirements?: string[];
  mapping_notes?: string;
}

export interface EvidenceRequirement {
  evidence_type: string;
  description: string;
  satisfies_nist?: boolean;
  satisfies_va_overlay?: boolean;
}

export interface CrossReference {
  control_id: string;
  family: string;
  relationship_description: string;
  shared_evidence_types?: string[];
}

export interface CatalogEnhancement {
  enhancement_id: string;
  enhancement_name: string;
  status: ControlStatus;
  nist_800_53: CatalogNist;
  va_overlay?: VaOverlay;
  plain_english_explanation?: string;
  evidence_required?: EvidenceRequirement[];
}

export interface CatalogControl {
  control_id: string;
  control_name: string;
  status: ControlStatus;
  control_type?: ControlType[];
  nist_800_53: CatalogNist;
  control_enhancements?: CatalogEnhancement[];
  va_overlay?: VaOverlay;
  plain_english_explanation?: string;
  evidence_required?: EvidenceRequirement[];
  cross_reference_controls?: CrossReference[];
}

export interface CatalogFamily {
  family_id: string;
  family_name: string;
  family_description: string;
  controls: CatalogControl[];
}

export interface CatalogMetadata {
  sources?: string[];
  reference_url?: string;
  generated_date?: string;
  schema_version?: string;
  notes?: string;
}

export interface Catalog {
  metadata?: CatalogMetadata;
  control_families: CatalogFamily[];
}

/* ----------------------------------------------------------------- evidence */

export const IMPLEMENTATION_STATUSES = [
  'not_started',
  'planned',
  'partially_implemented',
  'implemented',
  'inherited',
  'not_applicable',
  'alternative_implementation',
] as const;
export type ImplementationStatus = (typeof IMPLEMENTATION_STATUSES)[number];

export type ArtifactKind = 'file' | 'url' | 'diagram' | 'text';

export type ScriptLanguage = 'powershell';

/** How a collection script hands its evidence back to the app. */
export type ScriptOutputMode = 'text' | 'image';

/** Chain-of-custody detail for an artifact produced by running a collection script. */
export interface ScriptProvenance {
  language: ScriptLanguage;
  /** Verbatim script source, kept so the collection can be re-run and reviewed. */
  source: string;
  outputMode: ScriptOutputMode;
  ranAt: string;
  exitCode: number;
  durationMs: number;
  /** Machine the script ran on, recorded for the assessor. */
  host: string;
  runBy: string;
  stderr: string;
}

export interface Artifact {
  id: string;
  evidenceType: string;
  title: string;
  description: string;
  kind: ArtifactKind;
  /** Workspace-relative path, e.g. attachments/AC/AC-2_1__20260924T1530__diagram.png */
  filePath?: string;
  fileName?: string;
  mimeType?: string;
  sizeBytes?: number;
  sha256?: string;
  url?: string;
  mermaid?: string;
  body?: string;
  /** Present when the artifact was generated by a collection script rather than picked by hand. */
  script?: ScriptProvenance;
  collectedAt?: string;
  collectedBy?: string;
  recurrence?: ArtifactRecurrence;
  /** View-only: set on artifacts shown in a control that does not own them; never persisted. */
  sharedFrom?: string;
}

/** Lexical editor state serialised as JSON, plus a derived plain-text projection. */
export interface RichText {
  json: string | null;
  text: string;
}

export interface Narrative {
  implementation: RichText;
  processDescription: RichText;
  whyCompliant: RichText;
  limitations: RichText;
}

export interface OdpResponse {
  parameterId: string;
  label: string;
  value: string;
  source: 'nist' | 'va';
}

export interface ObjectiveResponse {
  objectiveIndex: number;
  met: boolean | null;
  note: string;
}

export interface ProcessStep {
  id: string;
  order: number;
  actor: string;
  action: string;
  system: string;
  frequency: string;
  evidenceRef: string;
}

export interface Ownership {
  /** The `id` of one of the settings' responsible roles (an OSCAL role-id token); older records may hold free text. */
  responsibleRole: string;
  owner: string;
  poc: string;
}

/** A responsible role offered in the Ownership section, with the default contact filled in when it is chosen. */
export interface ResponsibleRole {
  /** Written to the OSCAL SSP as `role-id`; fixed once created. */
  id: string;
  label: string;
  name: string;
  email: string;
}

export interface EvidenceDates {
  implementedOn: string | null;
  lastReviewedOn: string | null;
  nextReviewDue: string | null;
  evidenceAsOf: string | null;
}

export interface PoamEntry {
  hasFinding: boolean;
  findingId: string;
  severity: 'low' | 'moderate' | 'high' | 'critical' | '';
  remediationPlan: string;
  dueDate: string | null;
  /** Ids of `Artifact`s in the same record holding the POA&M record, waiver or closure proof. */
  artifactIds: string[];
}

/* ------------------------------------------------------ recurring evidence */

export const RECURRING_FREQUENCIES = [
  'annual',
  'semiannual',
  'quarterly',
  'monthly',
  'continuous',
  'org_defined',
] as const;
export type RecurringFrequency = (typeof RECURRING_FREQUENCIES)[number];

export type RecurringStatus = 'current' | 'due_soon' | 'overdue' | 'no_evidence_on_file';

/** Evidence content captured for one earlier collection cycle of a recurring artifact. */
export interface ArtifactCycle {
  id: string;
  /** e.g. "FY2026" or "2026" depending on the workspace cycle basis. */
  cycleLabel: string;
  collectedAt?: string;
  collectedBy?: string;
  /** Archived cycles stay on disk but drop out of retention counting and exports. */
  archived: boolean;
  filePath?: string;
  fileName?: string;
  mimeType?: string;
  sizeBytes?: number;
  sha256?: string;
  url?: string;
  body?: string;
  mermaid?: string;
  script?: ScriptProvenance;
}

/** Present when an artifact must be re-collected on a cadence. The artifact itself holds the current cycle. */
export interface ArtifactRecurrence {
  frequencyType: RecurringFrequency;
  /** Free text used when `frequencyType` is `org_defined`, e.g. "per FISMA minimum". */
  frequencyDetail: string;
  /** How many cycles must remain on file, including the current one. */
  retentionPeriods: number;
  notes: string;
  /** Earlier cycles, newest first. */
  history: ArtifactCycle[];
}


export interface ObjectiveCoverage {
  /** Index into the control's assessment objectives; absent on evaluations saved before JSON responses. */
  objectiveIndex?: number;
  objective: string;
  covered: boolean;
  rationale: string;
}

export interface AiEvaluation {
  id: string;
  at: string;
  promptVersion: number;
  inputHash: string;
  score: number;
  verdict: 'satisfied' | 'other_than_satisfied' | 'insufficient_detail';
  strengths: string[];
  gaps: string[];
  objectiveCoverage: ObjectiveCoverage[];
  suggestedRewrite: string;
  renderedPrompt: string;
  /** The model's JSON reply, kept for audit. */
  rawResponse?: string;
}

export interface ChangeLogEntry {
  at: string;
  field: string;
  from: string;
  to: string;
  by: string;
}

export interface EvidenceRecord {
  controlId: string;
  familyId: string;
  isEnhancement: boolean;
  parentControlId?: string;
  implementationStatus: ImplementationStatus;
  inScope: boolean;
  naJustification: string;
  origination: ControlDesignation;
  narrative: Narrative;
  odpResponses: OdpResponse[];
  objectiveResponses: ObjectiveResponse[];
  processSteps: ProcessStep[];
  artifacts: Artifact[];
  /** Ids of artifacts owned by other controls that also serve as evidence here. */
  linkedArtifactIds: string[];
  ownership: Ownership;
  dates: EvidenceDates;
  poam: PoamEntry;
  aiEvaluations: AiEvaluation[];
  tags: string[];
  changeLog: ChangeLogEntry[];
  updatedAt: string;
}

export type EvidenceMap = Record<string, EvidenceRecord>;

/* ----------------------------------------------------------------- settings */

export interface PromptVersion {
  version: number;
  savedAt: string;
  template: string;
}

export interface AppSettings {
  systemName: string;
  systemId: string;
  organization: string;
  currentUser: string;
  /** Impact level driving the default baseline selection. */
  baseline: Baseline;
  frameworkMode: FrameworkMode;
  lastAtoDate: string | null;
  nextAtoDate: string | null;
  /** Evidence older than this many days is flagged stale on the dashboard. */
  evidenceStaleAfterDays: number;
  /** How far ahead of a recurring due date an item is flagged "due soon". */
  recurringDueSoonDays: number;
  /** Whether recurring cycles are labelled by fiscal year (FY2026) or calendar year. */
  cycleBasis: 'fiscal' | 'calendar';
  /** 1-12. Federal fiscal years start in October. */
  fiscalYearStartMonth: number;
  promptTemplate: string;
  promptVersion: number;
  promptHistory: PromptVersion[];
  themeMode: 'light' | 'dark';
  /** Roles offered on a control, each with a default name and email applied when it is chosen. */
  responsibleRoles: ResponsibleRole[];
  ai: AiSettings;
}

export type AiProvider = 'builtin' | 'azure-openai' | 'tanstack-openai';
export type AzureCloud = 'commercial' | 'government';

/** Azure OpenAI connection settings. Authentication is the signed-in user's Entra ID token (MSAL Node); no secrets are stored here. */
export interface AiSettings {
  provider: AiProvider;
  /** Azure OpenAI resource or API Management gateway base URL, e.g. https://my-gateway.azure-api.us/api */
  endpoint: string;
  /** Deployment name as created in Azure AI Foundry, not the model name. */
  deployment: string;
  apiVersion: string;
  /** Application (client) ID of the public-client Entra app registration used for sign-in. */
  clientId: string;
  /** Entra token scope; blank uses Azure OpenAI's (cognitiveservices) scope for the selected cloud. */
  tokenScope: string;
  cloud: AzureCloud;
  /** Optional Entra tenant to sign in to; blank uses the default tenant of the signed-in account. */
  tenantId: string;
  /** Null omits the parameter (some reasoning models reject it). */
  temperature: number | null;
  /** Null lets the service decide. */
  maxOutputTokens: number | null;
  timeoutSeconds: number;
  /** Per-narrative character cap when drafting from related controls; longer narratives are truncated in the prompt. */
  relatedNarrativeMaxChars: number;
  /** Ask the service to guarantee a JSON reply (`response_format: json_object`). */
  jsonMode: boolean;
  /** TanStack AI OpenAI adapter: model id, e.g. gpt-5.2. The API key is stored encrypted by the main process, never here. */
  openaiModel: string;
  /** 'azure' targets an Azure OpenAI deployment (endpoint/deployment/apiVersion above) with the stored key as `api-key`. */
  openaiService: 'openai' | 'azure';
  /** Optional OpenAI organization ID. */
  openaiOrganization: string;
  /** Optional base URL override; blank uses https://api.openai.com/v1. */
  openaiBaseUrl: string;
}

export interface AiConnectionTestResult {
  ok: boolean;
  latencyMs: number;
  message: string;
  /** Likely cause and next step when the test fails. */
  hint?: string;
  model?: string;
}

/* ---------------------------------------------------------------- transport */

export interface WorkspaceInfo {
  root: string;
  defaultRoot: string;
  dbPath: string;
  settingsPath: string;
  attachmentsDir: string;
}

/** Result of a backup/restore action that asks for a file. */
export interface FileActionResult {
  cancelled: boolean;
  path?: string;
}

export interface AiEvaluateRequest {
  controlId: string;
  controlName: string;
  narrative: string;
  controlStatement: string;
  discussion: string;
  assessmentObjectives: string[];
  /** The author's current answers, index-aligned with `assessmentObjectives`. */
  objectiveResponses: Array<{ met: boolean | null; note: string }>;
  requiredEvidenceTypes: string[];
  providedEvidenceTypes: string[];
  vaOdpValues: VaOdpValue[];
  vaSpecificRequirements: string[];
  /** User-edited prompt text to send instead of rendering the saved template. */
  promptOverride?: string;
}

export interface AiReviseRequest {
  controlId: string;
  controlName: string;
  controlStatement: string;
  supplementalGuidance: string;
  /** Verbatim 800-53 statement with its lettered items and [Assignment] blanks. */
  statementTemplate: string;
  narrative: string;
}

export interface AiRevision {
  revisedNarrative: string;
  /** Short assessor observations explaining what was changed or is still missing. */
  notes: string[];
  renderedPrompt: string;
}

export interface RelatedNarrative {
  controlId: string;
  controlName: string;
  narrative: string;
}

export interface AiRelatedDraftRequest {
  controlId: string;
  controlName: string;
  controlStatement: string;
  /** Verbatim 800-53 statement with its lettered items and [Assignment] blanks. */
  statementTemplate: string;
  supplementalGuidance: string;
  currentNarrative: string;
  related: RelatedNarrative[];
  /** Set by the main process from AI settings; overrides the default per-narrative cap. */
  maxNarrativeChars?: number;
}

export interface RelatedDraftElement {
  /** The statement element (verbatim) this draft addresses. */
  element: string;
  draft: string;
  /** Related control ids the draft drew on. */
  sources: string[];
}

export interface AiRelatedDraft {
  elements: RelatedDraftElement[];
  /** Statement elements the related narratives do not support. */
  gaps: string[];
  renderedPrompt: string;
}

export interface AiOdpSuggestRequest {
  controlId: string;
  controlName: string;
  /** Verbatim 800-53 statement with its lettered items and [Assignment] blanks. */
  statementTemplate: string;
  narrative: string;
  responsibleRole: string;
  owner: string;
  /** Evidence artifacts already attached to the control. */
  artifacts: Array<{ title: string; evidenceType: string; frequency: string }>;
  /** The blanks still to fill. */
  parameters: Array<{ parameterId: string; label: string }>;
}

export interface OdpSuggestion {
  parameterId: string;
  value: string;
  /** Where in the control's own information the value was found. */
  basis: string;
}

export interface AiOdpSuggestions {
  suggestions: OdpSuggestion[];
}

export interface ExportRequest {
  format: 'oscal' | 'csv' | 'markdown' | 'recurring-csv';
  contents: string;
  suggestedName: string;
}

export interface OscalPackageRequest {
  sspJson: string;
  /** Name of the SSP JSON inside the ZIP. */
  sspFileName: string;
  suggestedName: string;
}

export interface OscalPackageResult {
  cancelled: boolean;
  path?: string;
  fileCount?: number;
  /** Referenced files that were not found in the workspace. */
  missing?: string[];
}

export interface AttachmentRequest {
  controlId: string;
  familyId: string;
  single?: boolean;
}

/** One control's content read from an external OSCAL SSP (e.g. a ServiceNow export), already migrated to the app's OSCAL version. */
export interface OscalImportControl {
  /** Catalog form, e.g. `AC-2(1)`. */
  controlId: string;
  implementationStatus?: ImplementationStatus;
  origination?: ControlDesignation;
  narrative: string;
  remarks: string;
  naJustification: string;
  setParameters: Array<{ paramId: string; value: string }>;
  responsibleRole: string;
  owner: string;
  links: Array<{ title: string; url: string }>;
}

export interface OscalImportResult {
  cancelled: boolean;
  fileName?: string;
  /** `oscal-version` declared by the file. */
  sourceVersion?: string;
  targetVersion?: string;
  systemName?: string;
  controls?: OscalImportControl[];
  /** Migration and mapping notes to show the user. */
  notes?: string[];
}

export type AttachmentRenameRequest = {
  /** Workspace-relative path of the stored file. */
  filePath: string;
  controlId: string;
  /** `YYYY-MM-DD` */
  collectedOn: string;
} & (
  | { scheme?: 'artifact'; evidenceType: string; title: string }
  /** `CTRL_YYYY-MM-DD_poam`, or the same prefixed with `archive_`. */
  | { scheme: 'poam' | 'poam-archive' }
);

export interface AttachmentResult {
  cancelled: boolean;
  artifacts: Array<
    Pick<Artifact, 'filePath' | 'fileName' | 'mimeType' | 'sizeBytes' | 'sha256'>
  >;
}

export interface ScriptRunRequest {
  controlId: string;
  script: string;
  outputMode: ScriptOutputMode;
  /** Base name for the saved evidence file, without extension. */
  fileNameHint?: string;
  /** Hard kill deadline. Clamped by the main process. */
  timeoutMs?: number;
}

export interface ScriptRunResult {
  cancelled: boolean;
  ok: boolean;
  exitCode: number;
  durationMs: number;
  ranAt: string;
  host: string;
  /** Captured stdout, truncated for display. */
  stdout: string;
  stderr: string;
  timedOut: boolean;
  error?: string;
  artifact?: Pick<Artifact, 'filePath' | 'fileName' | 'mimeType' | 'sizeBytes' | 'sha256'>;
}

/** One top-level bullet of a control narrative, with any list items beneath it. */
export interface SopBullet {
  bullet_text: string;
  sub_bullets: Array<{ text: string }>;
}

export interface SopControlInput {
  id: string;
  name: string;
  narrative: SopBullet[];
  /** File names of the evidence artifacts held for the control. */
  artifacts: string[];
  enhancements: Array<{ id: string; name: string; narrative: SopBullet[]; artifacts: string[] }>;
}

export interface SopFamilyInput {
  familyId: string;
  familyName: string;
  controls: SopControlInput[];
}

export interface SopExportRequest {
  families: SopFamilyInput[];
}

export interface WipeResult {
  recordsDeleted: number;
  filesDeleted: number;
}

export interface SopExportResult {
  cancelled: boolean;
  path?: string;
  familyCount?: number;
}

/** The surface exposed on `window.grc` by the preload bridge. */
export interface GrcBridge {
  getWorkspace(): Promise<WorkspaceInfo>;
  loadCatalog(): Promise<Catalog>;
  loadEvidence(): Promise<EvidenceMap>;
  saveEvidence(records: EvidenceRecord[]): Promise<{ savedAt: string }>;
  deleteEvidence(controlId: string): Promise<{ ok: true }>;
  loadSettings(): Promise<AppSettings>;
  saveSettings(settings: AppSettings): Promise<AppSettings>;
  addAttachments(req: AttachmentRequest): Promise<AttachmentResult>;
  readAttachment(relPath: string): Promise<string | null>;
  revealAttachment(relPath: string): Promise<void>;
  renameAttachment(req: AttachmentRenameRequest): Promise<Pick<Artifact, 'filePath' | 'fileName'>>;
  deleteAttachments(relPaths: string[]): Promise<{ deleted: number }>;
  runScript(req: ScriptRunRequest): Promise<ScriptRunResult>;
  aiEvaluate(req: AiEvaluateRequest): Promise<AiEvaluation>;
  aiRevise(req: AiReviseRequest): Promise<AiRevision>;
  aiRelatedDraft(req: AiRelatedDraftRequest): Promise<AiRelatedDraft>;
  aiSuggestOdp(req: AiOdpSuggestRequest): Promise<AiOdpSuggestions>;
  exportFile(req: ExportRequest): Promise<{ cancelled: boolean; path?: string }>;
  exportOscalPackage(req: OscalPackageRequest): Promise<OscalPackageResult>;
  exportSopWord(req: SopExportRequest): Promise<SopExportResult>;
  /** Deletes all attachments and control data; `confirmation` must be the word DELETE. */
  wipeControlData(confirmation: string): Promise<WipeResult>;
  importOscalSsp(): Promise<OscalImportResult>;
  backupConfig(): Promise<FileActionResult>;
  restoreConfig(): Promise<FileActionResult>;
  backupDatabase(): Promise<FileActionResult>;
  restoreDatabase(): Promise<FileActionResult>;
  /** Pick a new workspace folder (null result = cancelled). Existing data is not moved. */
  chooseWorkspaceLocation(): Promise<WorkspaceInfo | null>;
  resetWorkspaceLocation(): Promise<WorkspaceInfo>;
  /** Tests the given (possibly unsaved) settings, signing in first if needed. */
  aiTestConnection(settings: AiSettings): Promise<AiConnectionTestResult>;
  /** Forgets cached Entra sign-ins so the next request signs in again. */
  aiSignOut(): Promise<void>;
  /** Opens the system browser for Entra sign-in; returns the signed-in account name. */
  aiSignIn(settings: AiSettings): Promise<string | null>;
  aiSignedInAccount(settings: AiSettings): Promise<string | null>;
  /** Stores the OpenAI API key encrypted with the OS account; it is never returned to the renderer. */
  aiSetApiKey(apiKey: string): Promise<void>;
  aiClearApiKey(): Promise<void>;
  aiHasApiKey(): Promise<boolean>;
  openWorkspaceFolder(): Promise<void>;
}

declare global {
  interface Window {
    grc: GrcBridge;
  }
}
